"""initial schema

Revision ID: f6f4f15a97e1
Revises: 
Create Date: 2026-09-02 15:38:28.538113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f4f15a97e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('loop_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('data_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('blocking_issue', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('eda_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('target_distribution_notes', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('evaluation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('metric_optimized', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_threshold', sa.Float(), nullable=False),
    sa.Column('pass_fail', sa.String(), nullable=False),
    sa.Column('model_artifact_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('history_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('problem_specs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('target_column', sa.String(), nullable=False),
    sa.Column('success_metric', sa.String(), nullable=False),
    sa.Column('metric_threshold', sa.Float(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('trace_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('best_cv_score', sa.Float(), nullable=False),
    sa.Column('metric_optimized', sa.String(), nullable=False),
    sa.Column('search_budget_used', sa.Integer(), nullable=False),
    sa.Column('search_budget_total', sa.Integer(), nullable=False),
    sa.Column('convergence_notes', sa.String(), nullable=False),
    sa.Column('converged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.run_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('class_balance_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_profile_id', sa.Integer(), nullable=False),
    sa.Column('class_label', sa.String(), nullable=False),
    sa.Column('proportion', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['data_profile_id'], ['data_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cleaning_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_profile_id', sa.Integer(), nullable=False),
    sa.Column('column', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_profile_id'], ['data_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('column_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dtype', sa.String(), nullable=False),
    sa.Column('missing_pct', sa.Float(), nullable=False),
    sa.Column('is_target', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['data_profile_id'], ['data_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confusion_matrix_cells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_report_id', sa.Integer(), nullable=False),
    sa.Column('row_idx', sa.Integer(), nullable=False),
    sa.Column('col_idx', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_report_id'], ['evaluation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_profile_warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_profile_id', sa.Integer(), nullable=False),
    sa.Column('warning_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_profile_id'], ['data_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_quality_warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eda_report_id', sa.Integer(), nullable=False),
    sa.Column('warning_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eda_report_id'], ['eda_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_report_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('recommended_next_step', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_report_id'], ['evaluation_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_report_id')
    )
    op.create_table('feature_correlations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eda_report_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['eda_report_id'], ['eda_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eda_report_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eda_report_id'], ['eda_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_feature_names',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eda_report_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eda_report_id'], ['eda_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leakage_warnings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eda_report_id', sa.Integer(), nullable=False),
    sa.Column('warning_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['eda_report_id'], ['eda_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlier_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_profile_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['data_profile_id'], ['data_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_constraints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('problem_spec_id', sa.Integer(), nullable=False),
    sa.Column('max_training_seconds', sa.Integer(), nullable=True),
    sa.Column('max_tuning_trials', sa.Integer(), nullable=True),
    sa.Column('interpretability_required', sa.Boolean(), nullable=False),
    sa.Column('max_loop_backs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_spec_id'], ['problem_specs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_spec_id')
    )
    op.create_table('residual_summary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_report_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_report_id'], ['evaluation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_metric_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_report_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_report_id'], ['evaluation_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tuning_result_id', sa.Integer(), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tuning_result_id'], ['tuning_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tuning_best_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tuning_result_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(), nullable=False),
    sa.Column('param_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tuning_result_id'], ['tuning_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trial_record_params',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trial_record_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(), nullable=False),
    sa.Column('param_value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trial_record_id'], ['trial_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial_record_params')
    op.drop_table('tuning_best_params')
    op.drop_table('trial_records')
    op.drop_table('test_metric_entries')
    op.drop_table('residual_summary_entries')
    op.drop_table('pipeline_constraints')
    op.drop_table('outlier_flags')
    op.drop_table('leakage_warnings')
    op.drop_table('final_feature_names')
    op.drop_table('feature_decisions')
    op.drop_table('feature_correlations')
    op.drop_table('failure_analyses')
    op.drop_table('data_quality_warnings')
    op.drop_table('data_profile_warnings')
    op.drop_table('confusion_matrix_cells')
    op.drop_table('column_schemas')
    op.drop_table('cleaning_actions')
    op.drop_table('class_balance_entries')
    op.drop_table('tuning_results')
    op.drop_table('trace_entries')
    op.drop_table('problem_specs')
    op.drop_table('history_entries')
    op.drop_table('evaluation_reports')
    op.drop_table('eda_reports')
    op.drop_table('data_profiles')
    op.drop_table('runs')
    # ### end Alembic commands ###
