"""
alembic/env.py

Generated by `alembic init alembic`, then customized in two places:
1. sqlalchemy.url comes from core.config.settings (the SAME settings
   object every other part of this project reads), not a hardcoded
   value in alembic.ini.
2. target_metadata = Base.metadata — but only AFTER importing
   db.models, which is what actually registers all 26 table classes
   onto that metadata. Importing db.base alone leaves target_metadata
   empty: autogenerate would then run successfully and produce a
   migration with empty upgrade()/downgrade() functions — no error,
   no tables, nothing telling you it failed silently.
"""

from logging.config import fileConfig

from alembic import context
from sqlalchemy import create_engine, pool

from core.config import settings
from db.base import Base
import db.models  # noqa: F401 — imported for its side effect only:
# registering every table class onto Base.metadata before it's read below.

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(settings.database_url, poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()